#cloud-config

package_update: true

runcmd:
  - curl -fsSL https://raw.githubusercontent.com/EleazarAldayG/app-asistencia-con-fallas/refs/heads/main/azure/vm-setup.sh -o /home/dev/vm-setup.sh
  - chmod +x /home/dev/vm-setup.sh
  - chown tdp:tdp /home/dev/vm-setup.sh
  - sudo -u tdp bash /home/dev/vm-setup.sh > /home/dev/setup.log 2>&1